In [62]:
import pandas as pd
import os
import sys
import re
import pickle
sys.path.append("/home/onyxia/work/WP10_Cluster1_StatCodGen/codauto")
from structured import Structured
from codifier import Codifier

# Using Structured for German NACE

In [63]:
# Load the structure downloaded from the link provided earlier
path_struc_wz = r'./../resources'#/WP10_Cluster1_StatCodGen/de/wz_classification/' # Change the path to the location of the downloaded file
name_stuc_wz = 'WZ_2025-DE-2026-01-27-Gliederung.xlsx'
structure_wz_df = pd.read_excel(
    os.path.join(path_struc_wz, name_stuc_wz),
    sheet_name=1,
    dtype=str,
    skiprows=0,
    header=0,
    usecols=[0,2]
)
# For any classification, a DataFrame with two columns must be used: the first with the classification codes and the second with the titles.
# The codes must be provided in hierarchical order, meaning that parent classes must appear before their children.
structure_wz_df.head()

/opt/python/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Schlüssel WZ 2025                                              Titel
0                 A               Land- und Forstwirtschaft, Fischerei
1                01  Landwirtschaft, Jagd und damit verbundene Täti...
2              01.1               Anbau ein- und zweijähriger Pflanzen
3             01.11  Anbau von anderem Getreide als Reis sowie von ...
4           01.11.0  Anbau von anderem Getreide als Reis sowie von ...

In [65]:
# class StructuredWZ(Structured): 
#         """
#         Structured hierarchy for German NACE version called WZ (Wirtschaftszweigklassifikation)

#         Levels are determined strictly by the length of the classification code.
        
#         """
#         def get_level(self, code): # Structured child class specific to WZ
#             """
#             Structured hierarchy for German WZ
    
#             Parameters
#             ----------
#             code : str
#                 WZ classification code.
    
#             Returns
#             -------
#             int
#                 Hierarchical level based on code length
#             """
#             code = str(code).replace('.', '')      
#             return len(code)-1

In [67]:
# Generate the instance of StructuredWZ
wz_structure = StructuredWZ(
    structure_df=structure_wz_df,
    names_l=[
    'Section',
    'Division',
    'Group',
    'Class',
    'Subclass'
    ] # Names of the levels ordered from highest to lowest hierarchy
# As a best practice, it is recommended to use underscores instead of spaces and to avoid accents
)
wz_structure.level_dict

{0: 'Section', 1: 'Division', 2: 'Group', 3: 'Class', 4: 'Subclass'}

In [68]:
wz_structure.get_level('01.1')

2

In [69]:
wzs = wz_structure.load_structue(structure_wz_df)

In [70]:
wzs[wzs['level'] == 1]

,Schlüssel WZ 2025,Titel,level
1,01,"Landwirtschaft, Jagd und damit verbundene Täti...",1
78,02,Forstwirtschaft und Holzeinschlag,1
91,03,Fischerei und Aquakultur,1
106,05,Kohlenbergbau,1
113,06,Gewinnung von Erdöl und Erdgas,1
...,...,...,...
1957,95,Reparatur und Instandhaltung von Datenverarbei...,1
1986,96,Erbringung von überwiegend persönlichen Dienst...,1
2014,97,Private Haushalte mit Hauspersonal,1
2018,98,Herstellung von Waren und Erbringung von Diens...,1
2026,99,Exterritoriale Organisationen und Körperschaften,1

# Using Codifier for German NACE

In [71]:
# WZ test data
train_df = pd.DataFrame({'label': ['35122', '78202', '23200', '71126'], 'text': ['text1', 'text2', 'word1', 'word2']}) 
test_df = pd.DataFrame({'label': ['35122', '78202'], 'text': ['tekst3', 'tekstt2'], 'source': ['s1', 's1']})